[package]
name = "mmtk_v8"
version = "0.0.1"
authors = [" <>"]

[lib]
name = "mmtk_v8"
# be careful - LTO is only allowed for certain crate types
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
libc = "0.2"
lazy_static = "1.1"

[dependencies.mmtk]
git = "ssh://git@github.com/mmtk/mmtk-core.git"
rev = "36744788016f0d66d0539bde62a68f078b9e275c"


[features]
default = []
nogc = ["mmtk/nogc"]
