name: V8 Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    with:
      test_v8: true
      binding_ref: ${{ github.sha }}

  style_check:
    uses: ./.github/workflows/tests.yml
    with:
      style_check: true
      binding_ref: ${{ github.sha }}
