name: V8 Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

jobs:
  test:
    runs-on: [self-hosted, linux, freq-scaling-on]
    if: contains(github.event.pull_request.labels.*.name, 'PR-approved')
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
        with:
          # CI_ACCESS_TOKEN is a secret set with the repo
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          submodules: true
      
      - name: Set credential for cargo dependency
        run: sed -i 's/ssh:\/\/git@github.com\/mmtk/https:\/\/javadamiri:${{ secrets.CI_ACCESS_TOKEN }}@github.com\/mmtk/g' mmtk/Cargo.toml
      
      - name: Set env
        run: |
          echo "RUSTUP_TOOLCHAIN=nightly-2020-07-08" >> $GITHUB_ENV
          echo "V8_ROOT=$GITHUB_WORKSPACE/v8-deps" >> $GITHUB_ENV

      # Be aware that any changes made to the following steps should be made to ci-test.sh as well.
      # MMTk core tests the V8 binding by invoking ci-test.sh.

      - name: Setup Environments
        run: ./.github/scripts/ci-setup.sh
      
      - name: Build MMTk NOGC
        run: ./.github/scripts/build-mmtk.sh
        
      - name: Get V8 Sources
        run: ./.github/scripts/get-v8.sh
      
      - name: Build V8 with MMTk
        run: ./.github/scripts/build-v8.sh
      
      # The following two steps are currently failing, so they are not included in ci-test.sh.
      # Once they pass, we should add them to ci-test.sh      
      - name: Run V8 regression Tests
        run: ./.github/scripts/run-regress.sh
        continue-on-error: true
        
      - name: Run V8 unittests Tests
        run: ./.github/scripts/run-unittests.sh
        continue-on-error: true
      
      - name: Run V8 Benchmark Tests
        run: ./.github/scripts/run-benchmarks.sh
